// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpVy-n7ScMZCT_9bEvVlxjFkRUg16Zrmk',
    appId: '1:615647597249:web:da5a2efdf5ba646acd7a40',
    messagingSenderId: '615647597249',
    projectId: 'carsmarket-8b9a8',
    authDomain: 'carsmarket-8b9a8.firebaseapp.com',
    storageBucket: 'carsmarket-8b9a8.firebasestorage.app',
    measurementId: 'G-FZH56TGHFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtCcSZ_0DSFPboP-H4jtVkoQT-8tbgtSk',
    appId: '1:615647597249:android:cb93143f85938ecfcd7a40',
    messagingSenderId: '615647597249',
    projectId: 'carsmarket-8b9a8',
    storageBucket: 'carsmarket-8b9a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5-mtkjVm3Ejs28JWurHZRNTXgfkn6EDQ',
    appId: '1:615647597249:ios:ebdbf5bf591b4836cd7a40',
    messagingSenderId: '615647597249',
    projectId: 'carsmarket-8b9a8',
    storageBucket: 'carsmarket-8b9a8.firebasestorage.app',
    iosBundleId: 'com.example.carsMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5-mtkjVm3Ejs28JWurHZRNTXgfkn6EDQ',
    appId: '1:615647597249:ios:ebdbf5bf591b4836cd7a40',
    messagingSenderId: '615647597249',
    projectId: 'carsmarket-8b9a8',
    storageBucket: 'carsmarket-8b9a8.firebasestorage.app',
    iosBundleId: 'com.example.carsMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpVy-n7ScMZCT_9bEvVlxjFkRUg16Zrmk',
    appId: '1:615647597249:web:185b46e0b23c3a37cd7a40',
    messagingSenderId: '615647597249',
    projectId: 'carsmarket-8b9a8',
    authDomain: 'carsmarket-8b9a8.firebaseapp.com',
    storageBucket: 'carsmarket-8b9a8.firebasestorage.app',
    measurementId: 'G-DJWCX8V09P',
  );
}
