import 'package:data/models/failure/failure.dart';
import 'package:error_handler/error_handler/auth_error_handler/auth_error_codes.dart';
import 'package:error_handler/error_handler/auth_error_handler/auth_extensions.dart';
import 'package:error_handler/error_handler/auth_error_handler/auth_type.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class AuthErrorHandler implements Exception {
  // late Failure failure;
  // AuthErrorHandler.handelError(dynamic error) {
  //   if (error is AuthApiException) {
  //     failure = handelError(error);
  //   } else {
  //     failure = AuthErrorType.unknown.getFailure();
  //   }
  // }
static  Failure handelError(AuthException  error) {
    switch (error.code) {
      case AuthErrorCodes.anonymousProviderDisabled:
        return AuthErrorType.anonymousProviderDisabled.getFailure();
      case AuthErrorCodes.badCodeVerifier:
        return AuthErrorType.badCodeVerifier.getFailure();
      case AuthErrorCodes.badJson:
        return AuthErrorType.badJson.getFailure();
      case AuthErrorCodes.badJwt:
        return AuthErrorType.badJwt.getFailure();
      case AuthErrorCodes.badOauthCallback:
        return AuthErrorType.badOauthCallback.getFailure();
      case AuthErrorCodes.badOauthState:
        return AuthErrorType.badOauthState.getFailure();
      case AuthErrorCodes.captchaFailed:
        return AuthErrorType.captchaFailed.getFailure();
      case AuthErrorCodes.conflict:
        return AuthErrorType.conflict.getFailure();
      case AuthErrorCodes.emailAddressInvalid:
        return AuthErrorType.emailAddressInvalid.getFailure();
      case AuthErrorCodes.emailAddressNotAuthorized:
        return AuthErrorType.emailAddressNotAuthorized.getFailure();
      case AuthErrorCodes.emailConflictIdentityNotDeletable:
        return AuthErrorType.emailConflictIdentityNotDeletable.getFailure();
      case AuthErrorCodes.emailExists:
        return AuthErrorType.emailExists.getFailure();
      case AuthErrorCodes.emailNotConfirmed:
        return AuthErrorType.emailNotConfirmed.getFailure();
      case AuthErrorCodes.emailProviderDisabled:
        return AuthErrorType.emailProviderDisabled.getFailure();
      case AuthErrorCodes.flowStateExpired:
        return AuthErrorType.flowStateExpired.getFailure();
      case AuthErrorCodes.flowStateNotFound:
        return AuthErrorType.flowStateNotFound.getFailure();
      case AuthErrorCodes.hookPayloadInvalidContentType:
        return AuthErrorType.hookPayloadInvalidContentType.getFailure();
      case AuthErrorCodes.hookPayloadOverSizeLimit:
        return AuthErrorType.hookPayloadOverSizeLimit.getFailure();
      case AuthErrorCodes.hookTimeout:
        return AuthErrorType.hookTimeout.getFailure();
      case AuthErrorCodes.hookTimeoutAfterRetry:
        return AuthErrorType.hookTimeoutAfterRetry.getFailure();
      case AuthErrorCodes.identityAlreadyExists:
        return AuthErrorType.identityAlreadyExists.getFailure();
      case AuthErrorCodes.identityNotFound:
        return AuthErrorType.identityNotFound.getFailure();
      case AuthErrorCodes.insufficientAal:
        return AuthErrorType.insufficientAal.getFailure();
      case AuthErrorCodes.invalidCredentials:
        return AuthErrorType.invalidCredentials.getFailure();
      case AuthErrorCodes.inviteNotFound:
        return AuthErrorType.inviteNotFound.getFailure();
      case AuthErrorCodes.manualLinkingDisabled:
        return AuthErrorType.manualLinkingDisabled.getFailure();
      case AuthErrorCodes.mfaChallengeExpired:
        return AuthErrorType.mfaChallengeExpired.getFailure();
      case AuthErrorCodes.mfaFactorNameConflict:
        return AuthErrorType.mfaFactorNameConflict.getFailure();
      case AuthErrorCodes.mfaFactorNotFound:
        return AuthErrorType.mfaFactorNotFound.getFailure();
      case AuthErrorCodes.mfaIpAddressMismatch:
        return AuthErrorType.mfaIpAddressMismatch.getFailure();
      case AuthErrorCodes.mfaPhoneEnrollNotEnabled:
        return AuthErrorType.mfaPhoneEnrollNotEnabled.getFailure();
      case AuthErrorCodes.mfaPhoneVerifyNotEnabled:
        return AuthErrorType.mfaPhoneVerifyNotEnabled.getFailure();
      case AuthErrorCodes.mfaTotpEnrollNotEnabled:
        return AuthErrorType.mfaTotpEnrollNotEnabled.getFailure();
      case AuthErrorCodes.mfaTotpVerifyNotEnabled:
        return AuthErrorType.mfaTotpVerifyNotEnabled.getFailure();
      case AuthErrorCodes.mfaVerificationFailed:
        return AuthErrorType.mfaVerificationFailed.getFailure();
      case AuthErrorCodes.mfaVerificationRejected:
        return AuthErrorType.mfaVerificationRejected.getFailure();
      case AuthErrorCodes.mfaVerifiedFactorExists:
        return AuthErrorType.mfaVerifiedFactorExists.getFailure();
      case AuthErrorCodes.mfaWebAuthnEnrollNotEnabled:
        return AuthErrorType.mfaWebAuthnEnrollNotEnabled.getFailure();
      case AuthErrorCodes.mfaWebAuthnVerifyNotEnabled:
        return AuthErrorType.mfaWebAuthnVerifyNotEnabled.getFailure();
      case AuthErrorCodes.noAuthorization:
        return AuthErrorType.noAuthorization.getFailure();
      case AuthErrorCodes.notAdmin:
        return AuthErrorType.notAdmin.getFailure();
      case AuthErrorCodes.oauthProviderNotSupported:
        return AuthErrorType.oauthProviderNotSupported.getFailure();
      case AuthErrorCodes.otpDisabled:
        return AuthErrorType.otpDisabled.getFailure();
      case AuthErrorCodes.otpExpired:
        return AuthErrorType.otpExpired.getFailure();
      case AuthErrorCodes.overEmailSendRateLimit:
        return AuthErrorType.overEmailSendRateLimit.getFailure();
      case AuthErrorCodes.overRequestRateLimit:
        return AuthErrorType.overRequestRateLimit.getFailure();
      case AuthErrorCodes.overSmsSendRateLimit:
        return AuthErrorType.overSmsSendRateLimit.getFailure();
      case AuthErrorCodes.phoneExists:
        return AuthErrorType.phoneExists.getFailure();
      case AuthErrorCodes.phoneNotConfirmed:
        return AuthErrorType.phoneNotConfirmed.getFailure();
      case AuthErrorCodes.phoneProviderDisabled:
        return AuthErrorType.phoneProviderDisabled.getFailure();
      case AuthErrorCodes.providerDisabled:
        return AuthErrorType.providerDisabled.getFailure();
      case AuthErrorCodes.providerEmailNeedsVerification:
        return AuthErrorType.providerEmailNeedsVerification.getFailure();
      case AuthErrorCodes.reauthenticationNeeded:
        return AuthErrorType.reauthenticationNeeded.getFailure();
      case AuthErrorCodes.reauthenticationNotValid:
        return AuthErrorType.reauthenticationNotValid.getFailure();
      case AuthErrorCodes.refreshTokenAlreadyUsed:
        return AuthErrorType.refreshTokenAlreadyUsed.getFailure();
      case AuthErrorCodes.refreshTokenNotFound:
        return AuthErrorType.refreshTokenNotFound.getFailure();
      case AuthErrorCodes.requestTimeout:
        return AuthErrorType.requestTimeout.getFailure();
      case AuthErrorCodes.samePassword:
        return AuthErrorType.samePassword.getFailure();
      case AuthErrorCodes.samlAssertionNoEmail:
        return AuthErrorType.samlAssertionNoEmail.getFailure();
      case AuthErrorCodes.samlAssertionNoUserId:
        return AuthErrorType.samlAssertionNoUserId.getFailure();
      case AuthErrorCodes.samlEntityIdMismatch:
        return AuthErrorType.samlEntityIdMismatch.getFailure();
      case AuthErrorCodes.samlIdpAlreadyExists:
        return AuthErrorType.samlIdpAlreadyExists.getFailure();
      case AuthErrorCodes.samlIdpNotFound:
        return AuthErrorType.samlIdpNotFound.getFailure();
      case AuthErrorCodes.samlMetadataFetchFailed:
        return AuthErrorType.samlMetadataFetchFailed.getFailure();
      case AuthErrorCodes.samlProviderDisabled:
        return AuthErrorType.samlProviderDisabled.getFailure();
      case AuthErrorCodes.samlRelayStateExpired:
        return AuthErrorType.samlRelayStateExpired.getFailure();
      case AuthErrorCodes.samlRelayStateNotFound:
        return AuthErrorType.samlRelayStateNotFound.getFailure();
      case AuthErrorCodes.sessionExpired:
        return AuthErrorType.sessionExpired.getFailure();
      case AuthErrorCodes.sessionNotFound:
        return AuthErrorType.sessionNotFound.getFailure();
      case AuthErrorCodes.signupDisabled:
        return AuthErrorType.signupDisabled.getFailure();
      case AuthErrorCodes.singleIdentityNotDeletable:
        return AuthErrorType.singleIdentityNotDeletable.getFailure();
      case AuthErrorCodes.smsSendFailed:
        return AuthErrorType.smsSendFailed.getFailure();
      case AuthErrorCodes.ssoDomainAlreadyExists:
        return AuthErrorType.ssoDomainAlreadyExists.getFailure();
      case AuthErrorCodes.ssoProviderNotFound:
        return AuthErrorType.ssoProviderNotFound.getFailure();
      case AuthErrorCodes.tooManyEnrolledMfaFactors:
        return AuthErrorType.tooManyEnrolledMfaFactors.getFailure();
      case AuthErrorCodes.unexpectedAudience:
        return AuthErrorType.unexpectedAudience.getFailure();
      case AuthErrorCodes.unexpectedFailure:
        return AuthErrorType.unexpectedFailure.getFailure();
      case AuthErrorCodes.userAlreadyExists:
        return AuthErrorType.userAlreadyExists.getFailure();
      case AuthErrorCodes.userBanned:
        return AuthErrorType.userBanned.getFailure();
      case AuthErrorCodes.userNotFound:
        return AuthErrorType.userNotFound.getFailure();
      case AuthErrorCodes.userSsoManaged:
        return AuthErrorType.userSsoManaged.getFailure();
      case AuthErrorCodes.validationFailed:
        return AuthErrorType.validationFailed.getFailure();
      case AuthErrorCodes.weakPassword:
        return AuthErrorType.weakPassword.getFailure();
      default:
        return AuthErrorType.unknown.getFailure();
    }
  }
}
